groups:
  - name: metadata_service_alerts
    rules:
      # High Error Rate Alert
      - alert: HighErrorRate
        expr: |
          sum(rate(http_requests_total{status=~"5.."}[5m])) 
          / 
          sum(rate(http_requests_total[5m])) > 0.05
        for: 5m
        labels:
          severity: critical
        annotations:
          summary: High HTTP error rate
          description: "Error rate is {{ $value | humanizePercentage }} over the last 5 minutes"

      # Slow Response Time Alert
      - alert: SlowResponseTime
        expr: |
          histogram_quantile(0.95, sum(rate(http_request_duration_seconds_bucket[5m])) by (le)) > 1
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: Slow response time
          description: "95th percentile of response time is {{ $value | humanizeDuration }} over the last 5 minutes"

      # Database Connection Alert
      - alert: HighDatabaseConnections
        expr: db_connections_open > 80
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: High number of database connections
          description: "{{ $value }} database connections currently open"

      # Cache Performance Alert
      - alert: LowCacheHitRate
        expr: |
          sum(rate(cache_hits_total{cache="redis"}[5m])) 
          / 
          (sum(rate(cache_hits_total{cache="redis"}[5m])) + sum(rate(cache_misses_total{cache="redis"}[5m]))) < 0.7
        for: 10m
        labels:
          severity: warning
        annotations:
          summary: Low cache hit rate
          description: "Cache hit rate is {{ $value | humanizePercentage }} over the last 10 minutes"

      # AI Service Performance Alert
      - alert: AIServiceLatency
        expr: |
          histogram_quantile(0.95, sum(rate(ai_request_duration_seconds_bucket[5m])) by (le, operation)) > 5
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: High AI service latency
          description: "95th percentile of AI service latency is {{ $value | humanizeDuration }} for {{ $labels.operation }}"

      # Track Processing Alert
      - alert: HighTrackProcessingFailureRate
        expr: |
          sum(rate(tracks_processed_total{status="error"}[5m])) 
          / 
          sum(rate(tracks_processed_total[5m])) > 0.1
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: High track processing failure rate
          description: "Track processing failure rate is {{ $value | humanizePercentage }} over the last 5 minutes"

      # Active Users Drop Alert
      - alert: ActiveUsersDrop
        expr: |
          active_users < 10 and hour() > 9 and hour() < 18 and day_of_week() < 6
        for: 10m
        labels:
          severity: warning
        annotations:
          summary: Low number of active users
          description: "Only {{ $value }} active users in the last 5 minutes during business hours"

      # Subscription Alert
      - alert: SubscriptionImbalance
        expr: |
          abs(
            (subscriptions_by_plan{plan="enterprise"} - subscriptions_by_plan{plan="pro"}) 
            / 
            subscriptions_by_plan{plan="pro"}
          ) > 0.5
        for: 24h
        labels:
          severity: info
        annotations:
          summary: Unusual subscription distribution
          description: "Unusual ratio between enterprise and pro subscriptions"

      # System Resource Alerts
      - alert: HighMemoryUsage
        expr: process_resident_memory_bytes / process_virtual_memory_bytes > 0.8
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: High memory usage
          description: "Memory usage is at {{ $value | humanizePercentage }}"

      # API Quota Alert
      - alert: APIQuotaNearLimit
        expr: |
          sum(rate(http_requests_total{path=~"/api/v1/external/.*"}[1h])) > 8000
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: API quota near limit
          description: "External API requests approaching rate limit ({{ $value | humanize }} req/hour)" 